### ISSUE TITLE
Proto2 support for JSON encoding

### ISSUE THREAD

**Issue by rafayepes** [mransan/ocaml-protoc#124]
For some reason, JSON encoding seems to only support proto3 syntax. See `"Only proto3 syntax supported in JSON encoding"`.

Any particular reason why proto2 is not supported for JSON encoding?

**Comment by mransan** [comment]
Hi, there is no standard defined for proto2 encoding to JSON. While it would be possible to apply similar rules as what proto3 does it would still be a custom set of rules that might not be followed by other languages.

**Comment by mransan** [comment]
As mentioned above I would rather focus on proto3 for JSON.
