### ISSUE TITLE
New release with fixed proto3 support

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [mransan/ocaml-protoc#127]
https://github.com/mransan/ocaml-protoc/pull/117 was merged over a year ago, and it is pretty important for supporting proto3 out of the box, therefore I would like to ask for a release so we don't have to preprocess all proto3 files and add `packed` flags to them.

**Comment by XVilka** [comment]
Before crafting the new release it makes sense to :
- Dunify the build: https://github.com/mransan/ocaml-protoc/issues/134
- Add Travis CI/AppVeyor autobuild scripts: https://github.com/mransan/ocaml-protoc/issues/133
- Merge https://github.com/mransan/ocaml-protoc/pull/113
- Make sure it works well with OCaml 4.08 (maybe 4.09 too, depending on when it will happen).

**Comment by mransan** [comment]
ocaml-protoc 2.0 released with suggested changes.
