### ISSUE TITLE
oneof keyword name cannot be "message"

### ISSUE THREAD

**Issue by cyocum** [mransan/ocaml-protoc#129]
When running under 1.2.0, if the following .proto file is passed to `ocaml-protoc`:

```
syntax = "proto3";
package foo;

message Wrapper {
  oneof message {
    Source source = 1;
  }
}

message Source {
  string uri = 1;
  string data = 2;
}
```

It will cause a parse error: `messages/messages.proto:5:0: Parsing error.`

If the `oneof` name is changed to something else it will create the ml/mli files as expected.  Thus, the below will work:

```
syntax = "proto3";
package foo;

message Wrapper {
  oneof foo {
    Source source = 1;
  }
}

message Source {
  string uri = 1;
  string data = 2;
}
```

**Comment by mransan** [comment]
Fixed in #145 will start an opam release.
