### ISSUE TITLE
Switch to Dune build system

### ISSUE THREAD

**Issue by XVilka** [mransan/ocaml-protoc#134]
[Dune](https://dune.build) is de-facto a new building system standard for the OCaml universe. Also it reduces the buildscripts maintenance, improves building performance and eases running tests. It also streamlines publishing process with [dune-release](https://github.com/samoht/dune-release) scripts.

**Comment by mransan** [comment]
Feel free to send a commit. I have little time to work on this but can review happily.

**Comment by mransan** [comment]
work has started.

**Comment by mransan** [comment]
Implemented in #141
