### ISSUE TITLE
Enable Travis CI and add a badge here

### ISSUE THREAD

**Issue by XVilka** [mransan/ocaml-protoc#136]
It was merged, but not activated for the repo: https://travis-ci.com/mransan/ocaml-protoc shows 404

See https://docs.travis-ci.com/user/tutorial/ on how to activate it, and add the badge.

**Comment by mransan** [comment]
all done. 

Sorry I've been pretty inactive... but recently got a project that will get me back on the ocaml-protoc improvements.
