### ISSUE TITLE
Crash compiling Yojson use of empty messages

### ISSUE THREAD

**Issue by vphantom** [mransan/ocaml-protoc#160]
Hi! Thank you for your work. :smile: When compiling the use of an empty message, i.e.:

```protobuf
message Empty {}  // This line is fine
message Test {
  Empty empty = 1;  // This crashes
}
```

…I get a crash in Yojson mode:

```text
$ ocaml-protoc -binary -yojson -ml_out . test.proto
Generating ./test_types.mli
Generating ./test_types.ml
File "src/compilerlib/pb_codegen_decode_yojson.ml", line 31, characters 18-24: Assertion failed
```

Indeed, that's https://github.com/mransan/ocaml-protoc/blob/master/src/compilerlib/pb_codegen_decode_yojson.ml#L31

I know that the JSON representation should be an empty object (i.e. `` `Assoc []``) but not to the point of knowing how to contribute this. 😕

**Comment by Lupus** [comment]
`message Empty {}` also seems to omit the type from generated files with types, so support for empty protobuf messages is not really present in the library...

**Comment by Lupus** [comment]
I believe https://github.com/mransan/ocaml-protoc/pull/198 should address this issue.
