### ISSUE TITLE
release 2.1

### ISSUE THREAD

**Issue by c-cube** [mransan/ocaml-protoc#168]
It'd be nice to get a new release once things stabilize :)

**Comment by mransan** [comment]
It would actually take me a while to get the whole development environment. If you are able to do it please go ahead.

**Comment by c-cube** [comment]
is there a checklist of what to do for a release somewhere?

**Comment by mransan** [comment]
If you can run the integration test that test against the C++ protobuf compiler that would be it. After that it's a straightforward opam update.
