### ISSUE TITLE
optional's comeback

### ISSUE THREAD

**Issue by c-cube** [mransan/ocaml-protoc#172]
seems like proto3 supports `optional` now: https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0 :-)

**Comment by vphantom** [comment]
Wow! I guess not being able to test for presence in some languages (I could do it in Perl) started to bug enough people. I found <https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md> which explains it further.

Interestingly I just hit a related issue with the OCaml generated types: while a `string` or `uint32` field will become a `string` or `int` record field in OCaml, a `Something` field will become a `something option` on the OCaml side. That seems wrong to me, moreso with this here comeback. Shouldn't they behave like scalar values, in that `something` should not be an `option`, and all of _its_ fields be at their default values if not part of the data?

**Comment by c-cube** [comment]
with proto3, I think you're right, it shoudl contain a `something`. Alas we should also have a bitfield (like C++ does I think) to know what is present or not, because otherwise serializing objects means serializing the default values too, which can get expensive.

**Comment by c-cube** [comment]
I think using `optional string foo = 42;` is exactly where we should insert an option for now, and avoid emitting the field if not present. That's explicit and backward compatible.
