### ISSUE TITLE
Use latest Yojson

### ISSUE THREAD

**Issue by Lupus** [mransan/ocaml-protoc#189]
Latest Yojson library (version 2 and higher) has dropped legacy `json` type, would be nice to bump the version of required yojson library along with the corresponding change in code generator. It's very cosmetic change, no other APIs are affected and everything works just fine. See corresponding PR to `ocaml-protoc-yojson`: https://github.com/mransan/ocaml-protoc-yojson/pull/2

**Comment by c-cube** [comment]
Should we also move to `Yojson.Safe.t`? Seems like most projects use this variant…

**Comment by Lupus** [comment]
Probably it also makes sense. [ppx_yojson_conv ](https://github.com/janestreet/ppx_yojson_conv) is producing `Yojson.Safe` in generated code as well.
