### ISSUE TITLE
ppx_deriving_protobuf as backend

### ISSUE THREAD

**Issue by artemkin** [mransan/ocaml-protoc#62]
It would be great to use `ppx_deriving_protobuf` as a backend.

I mean generate ocaml with protobuf extension points like

```
message SearchRequest {
  required string query = 1;
  optional int32 page_number = 2;
  optional int32 result_per_page = 3;
}
```

becomes

```
type search_request = {
  query           : string     [@key 1];
  page_number     : int option [@key 2];
  result_per_page : int option [@key 3];
} [@@deriving protobuf]
```

**Comment by bendiken** [comment]
So long as that would be optional, since syntax extensions would be a problem to those of us who already use e.g. a preprocessor such as Cppo.

**Comment by artemkin** [comment]
Sure, I suggest adding it as an alternative codegen. We would be able to deriving `compare`, `sexp` and the rest in addition to `protobuf`.

**Comment by rgrinberg** [comment]
@bendiken Why should ppx syntax extensions be a problem for cppo users? You do have to run cppo before any ppx preprocessors but this isn't a big limitation.

**Comment by mransan** [comment]
So adding the  `ppx_deriving_protobuf` ppx extension is definitely an area I would like to explore. We would have to be careful to ensure that the generated code by the ppx is matching exactly the `.proto` file. For record it should be fairly easy but variant are trickier. 

For instance I don't know yet how to generate an OCaml type with ppx extension that would match the following `.proto` file:

```
message M {
  oneof {
    int32 i  = 1; 
    string s = 2; 
  }
  required f = 3; 
}
```

**Comment by XVilka** [comment]
Any decision on this by the way?

**Comment by mransan** [comment]
It is no feasible as the convention used in ppx_deriving_protobuf is not the same as the protobuf language.  As mentioned there are plenty of protobuf message which cannot be represented as an OCaml type with ppx_deriving_protobuf, it will simply not encode the data structure correctly.

ppx_protobug_deriving is only using the encoding part of protobuf, the language part is the OCaml type system itself. Our approach is different the language part is the protobuf message one.
